export const env = {
  API_BASE_URL: import.meta.env.VITE_API_BASE_URL,
  GOOGLE_API_KEY: import.meta.env.VITE_APP_GOOGLE_API_KEY,
  FRONTEND_URL: import.meta.env.VITE_APP_FRONTEND_URL,
  GOOGLE_OAUTH_CLIENT_KEY: import.meta.env.VITE_APP_GOOGLE_OAUTH_CLIENT_KEY,
  ENCRYPTION_KEY: import.meta.env.VITE_APP_ENCRYPTION_KEY,
  ENCRYPTION_IV: import.meta.env.VITE_APP_ENCRYPTION_IV,
};
